// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementSystem.Data;

namespace SchoolManagementSystem.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20211118095118_fourModiCourse")]
    partial class fourModiCourse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("SchoolManagementSystem.Models.CourseTable", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CourseDuration")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId1")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("StudentId1");

                    b.ToTable("CourseTable");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.StudentTable", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("StudentAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentGender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentPhone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.ToTable("StudentTable");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.CourseTable", b =>
                {
                    b.HasOne("SchoolManagementSystem.Models.StudentTable", "StudentId")
                        .WithMany("CourseId")
                        .HasForeignKey("StudentId1");

                    b.Navigation("StudentId");
                });

            modelBuilder.Entity("SchoolManagementSystem.Models.StudentTable", b =>
                {
                    b.Navigation("CourseId");
                });
#pragma warning restore 612, 618
        }
    }
}
